import Head from "next/head";
import React from "react";
import Sidebar from "../../components/Sidebar";
import { Flex, Spacer } from "@chakra-ui/react";

function Home() {
  return (
    <Flex height="100vh" maxWidth="1300px" ms="auto" me="auto" padding="0 10px">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </Flex>
  );
}

export default Home;
